CREATE TABLE users(
id INT AUTO_INCREMENT,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
age INT NOT NULL,
address VARCHAR(100) NOT NULL,
joining_date DATE,
PRIMARY KEY (id)
);

